server:
  port: 8090
spring:
  application:
    name: keycloak-auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.server-url}/realms/${app.keycloak.realm}
app:
  keycloak:
    admin:
      client-id: admin-cli
      client-secret: 1vnzZCt6TLtE1jjOvppdDsuRbLApTGb4
    realm: spring-boot
    server-url: http://localhost:9082
    grant-type: client_credentials